### ISSUE TITLE
"redirectUrl" became "returnUrl"

### ISSUE THREAD

**Issue by ozmachine** [pinecat/azure-ad-graph-expo#16]
Seems like "redirectUrl" became "returnUrl" in 9a3dbb90e19855fbf14c91194790684e2240542a. Took me quite a while to figure this out, because the example still uses "redirectUrl" in its props object (however you're still using redirectUrl in your authUrl value).

**Comment by pinecat** [comment]
Hi,

Thanks for the concern, and apologies for the delay in my response.  We are still using _redirectUrl_ elsewhere as well.
https://github.com/pinecat/azure-ad-graph-expo/blob/11947e72658ac523e3be7d49e1a80890bc1f99fa/AzureADGraph.js#L76

It is true, the example does not have _returnUrl_ in props.  This value isn't wholly needed, because, as you mentioned, it will fallback to `AuthSession.makeRedirectUri()` (i.e. _redirectUrl_).
https://github.com/pinecat/azure-ad-graph-expo/blob/11947e72658ac523e3be7d49e1a80890bc1f99fa/AzureADGraph.js#L132

That being said, this should be explained better in the documentation.  I will include a note, and add _returnUrl_ to props in the example.
